# Generated by Django 6.0.2 on 2026-04-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_role_id_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='per_day_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
